[logger]
level='DEBUG'
debug=true
[cors]
allow_origins=["*"]
allow_credentials=true
allow_methods=["*"]
allow_headers=["*"]
[auth]
secret_key="o2nLYp>w+}-.->89eFXW8m*)j6hsb_c8_>3K?UMztX7et%>5N2C!bksx}]0bux-G6dv}tmJZo]Nnw@wh2=zCCaFCq*iAc,yPZWU?"
algorithm="HS256"
token_timeout=300
[postgres]
host = "postgres"
port = 5432
database = "postgres"
user = "postgres"
password = "postgres"